version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
    overwrite: true
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/apache_install.sh
      timeout: 300
      runas: root
    - location: scripts/apache_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/apache_stop.sh
      timeout: 300
      
